---
title: C6318
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: f472860cd338dee15b4005db16ba09de1e314071
ms.sourcegitcommit: 21d667104199c2493accec20c2388cf674b195c3
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 02/08/2019
ms.locfileid: "55920892"
---
# <a name="c6318"></a>C6318
Uyarı C6318: Ill-tanımlı__try /\__except: exceptıon_contınue_search sabitini veya özel durum filtreleyen ifadede sıfır olarak değerlendirilen başka bir sabiti kullanın. Özel durum işleyici bloğu içindeki kod yürütülmez

 Bu uyarı, bu yapılandırılmış özel durum işleyicisinin korumalı bloğunda bir özel durum oluşursa özel durum nedeniyle işlenmeyecek olduğunu gösterir. sabiti `EXCECPTION_CONTINUE_SEARCH` özel durum filtre ifadesinde kullanılır.

 İşleyici bloğu değil çalıştırıldığı için bu kod özel durum işleyici bloğu olmayan korumalı bloğu eşdeğerdir.

## <a name="example"></a>Örnek
 Aşağıdaki kod bu uyarıyı üretir:

```
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 Bu uyarıyı düzeltmek için aşağıdaki kodu kullanın:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>Ayrıca Bkz.
 [try-except Deyimi](/cpp/cpp/try-except-statement)