---
title: C6318
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: corob-msft
ms.author: corob
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 683619442865a231742fdecba9e94a893d103144
ms.sourcegitcommit: 68f893f6e472df46f323db34a13a7034dccad25a
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 02/15/2020
ms.locfileid: "77267024"
---
# <a name="c6318"></a>C6318
Uyarı C6318: Hatalı tanımlanmış __try/\__except: özel durum filtre ifadesinde sıfır sonucunu veren sabit EXCEPTION_CONTINUE_SEARCH veya başka bir sabit kullanın. Özel durum işleyici bloğundaki kod yürütülmedi

 Bu uyarı, bu yapılandırılmış özel durum işleyicisinin korunan bloğunda bir özel durum oluşursa, özel durum filtre ifadesinde sabit `EXCECPTION_CONTINUE_SEARCH` kullanıldığı için özel durum işlenmeyeceğini gösterir.

 Bu kod, işleyici bloğu yürütülmediği için özel durum işleyici bloğu olmadan korunan bloğa eşdeğerdir.

## <a name="example"></a>Örnek
 Aşağıdaki kod bu uyarıyı oluşturur:

```cpp
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 Bu uyarıyı düzeltmek için aşağıdaki kodu kullanın:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>Ayrıca bkz.
 [try-except Deyimi](/cpp/cpp/try-except-statement)
