---
title: C6318
ms.date: 11/04/2016
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 6093aa96a8d4fc36e89bd5c35bb1c255f4d1645f
ms.sourcegitcommit: 42ea834b446ac65c679fa1043f853bea5f1c9c95
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 04/19/2018
---
# <a name="c6318"></a>C6318
C6318 Uyarı: hatalı tanımlanmış yapıda /\__except: sabit exceptıon_contınue_search ya da özel durum filtresi ifadesinde sıfır olarak değerlendirir başka bir sabit kullanın. Özel durum işleyici bloğundaki kod yürütülmedi

 Bu yapılandırılmış özel durum işleyicisi korumalı bloğunda bir özel durum oluşursa, özel durum nedeniyle işleneceğini değil, bu uyarıyı gösterir sabiti `EXCECPTION_CONTINUE_SEARCH` özel durum filtre ifadesinde kullanılır.

 İşleyici bloğu değil çalıştırıldığı için bu kodu özel durum işleyici bloğunun olmadan korunan blok eşdeğerdir.

## <a name="example"></a>Örnek
 Aşağıdaki kod bu uyarı üretir:

```
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 Bu uyarıyı çözmek için aşağıdaki kodu kullanın:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>Ayrıca Bkz.
 [try-except Deyimi](/cpp/cpp/try-except-statement)