---
title: C6318
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 47bb0843ab6048bbfa1b4ba881d3748a23de6dd9
ms.sourcegitcommit: 485ffaedb1ade71490f11cf05962add1718945cc
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 10/16/2019
ms.locfileid: "72449632"
---
# <a name="c6318"></a>C6318
Uyarı C6318: Hatalı tanımlanmış __try/@no__t -0 _Except: özel durum filtre ifadesinde sıfır sonucunu veren sabit EXCEPTION_CONTINUE_SEARCH veya başka bir sabit kullanın. Özel durum işleyici bloğundaki kod yürütülmedi

 Bu uyarı, bu yapılandırılmış özel durum işleyicisinin korunan bloğunda bir özel durum oluşursa, özel durum filtre ifadesinde `EXCECPTION_CONTINUE_SEARCH` ' ı kullanıldığı için özel durum işlenmeyecektir.

 Bu kod, işleyici bloğu yürütülmediği için özel durum işleyici bloğu olmadan korunan bloğa eşdeğerdir.

## <a name="example"></a>Örnek
 Aşağıdaki kod bu uyarıyı oluşturur:

```
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 Bu uyarıyı düzeltmek için aşağıdaki kodu kullanın:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>Ayrıca Bkz.
 [try-except Deyimi](/cpp/cpp/try-except-statement)
